### ISSUE TITLE
prettier is causing jsx format issue.

### ISSUE THREAD

**Issue by MContagious** [kelset/rn-full-pack#1]
prettier is formatting jsx differently and causing lint issues.
```
export default class extends Component {
    render() {
        return ( < Provider store = { store } >
            <
            App / >
            <
            /Provider>
        )
    }
}
```

**Comment by kelset** [comment]
That's weird, are you sure you have all the extensions installed & configured properly?

I think you'd need to check that ESLint + Prettier + Babel are properly setup. Maybe you are missing the `  "prettier.eslintIntegration": true,` setting.

**Comment by kelset** [comment]
Closing since got no followup
