### ISSUE TITLE
Change extensionDependencies to extensionPack in package.json

### ISSUE THREAD

**Issue by chakrihacker** [kelset/rn-full-pack#2]
Hello @kelset 

I like this extension pack, but can't disable few unwanted extensions. From this update https://code.visualstudio.com/updates/v1_26#_extension-packs-revisited
one can use `extensionPack` where dependent extensions can be disabled unlike `extensionDependencies`

**Comment by kelset** [comment]
hey thanks - I wasn't aware! I don't know when I'll have time to update this, if you can could you please do a PR for this? 🙇‍♂️
