### ISSUE TITLE
coloured barckets 

### ISSUE THREAD

**Issue by UltraAsta** [kelset/rn-full-pack#6]
this issue happed couple of minutes ago. Coloured brackets started to apper in my code even if I deleted the extention of the coloured brackets. I tried disabiling all extensions and retarted the computer but it still won't go away

**Comment by kelset** [comment]
that's because it has become a native feature of VSCode for a while: https://code.visualstudio.com/blogs/2021/09/29/bracket-pair-colorization?msclkid=e970e3e2cf8711ec9ba0c99449d8e09b

I actually need to update the pack to not make you install those, so thanks for surfacing!
